version: 2
registries:
  rub-nexus:
    type: maven-repository
    url: https://hydrogen.cloud.nds.rub.de/nexus/repository/maven-release/
    username: dependabot
    password: ${{secrets.DEPENDABOT_NEXUS_PASSWORD}}
  maven-central:
    type: maven-repository
    url: https://repo1.maven.org/maven2/
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      # Check for dependency updates on a daily basis
      interval: "daily"
    registries: "*"
    reviewers:
      - "tls-attacker/tls-attacker-extended"
